# Version de Docker-compose
version: '2.15.1'

services:
  frontend: 
    ## Indicar el directorio donde se encuentra el Dockerfile
    build:      
      context: ./frontend
      dockerfile: Dockerfile
    image: "reactjs-app-test-1"
    container_name: container-frontend
    ##Establecer los puertos que expondremos al exterior a que puerto de nuestra maquina se vinculara 
    ports:
      - "80:3000"
    networks:
      - WebApp

  backend:
    build:      
      context: ./backend
      dockerfile: Dockerfile
    image: "django-app-test-1"
    container_name: container-backend      
    ports:
      - "8080:8000"
    networks:
      - WebApp
      
networks:
  WebApp:
    name: networks_WebApp
    driver: bridge
