## Nombre
name: Publish Docker image
on: [push]
 paths:
   - 'nginx/index.html'
## ID de trabajo
jobs:
push_to_registries:
 name: Push Docker image
  runs-on: ubuntu-latest
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
## Iniciar sesion en DockerHUb      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
## Crear la imagen del contenedor y enviarla al repositorio
    - name: Build and push docker image
      uses: docker/build-push-action@v3
      with:
       push: true
       tags: user/app:latest
